name: GitHub Classroom Workflow

on:
  push:
    branches: [ main, master ]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - uses: actions/checkout@v4
    - uses: education/autograding@v1
